CREATE TABLE IF NOT EXISTS `user` (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    user_type VARCHAR(20) DEFAULT 'user',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    count INT DEFAULT 0,
    writer VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comment (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    seq INT NOT NULL,
    context TEXT NOT NULL,
    writer VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS search_log (
    idx INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50),
    message TEXT,
    searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
